![Kayak](https://seekvectorlogo.com/wp-content/uploads/2018/01/kayak-vector-logo.png)

# Plan your trip with Kayak 

## Company's description 📇

<a href="https://www.kayak.com" target="_blank">Kayak</a> is a travel search engine that helps user plan their next trip at the best price.

The company was founded in 2004 by Steve Hafner & Paul M. English. After a few rounds of fundraising, Kayak was acquired by <a href="https://www.bookingholdings.com/" target="_blank">Booking Holdings</a> which now holds: 

* <a href="https://booking.com/" target="_blank">Booking.com</a>
* <a href="https://kayak.com/" target="_blank">Kayak</a>
* <a href="https://www.priceline.com/" target="_blank">Priceline</a>
* <a href="https://www.agoda.com/" target="_blank">Agoda</a>
* <a href="https://Rentalcars.com/" target="_blank">RentalCars</a>
* <a href="https://www.opentable.com/" target="_blank">OpenTable</a>

With over \$300 million revenue a year, Kayak operates in almost all countries and all languages to help their users book travels accros the globe.

## Project 🚧

The marketing team needs help on a new project. After doing some user research, the team discovered that **70% of their users who are planning a trip would like to have more information about the destination they are going to**. 

In addition, user research shows that **people tend to be defiant about the information they are reading if they don't know the brand** which produced the content. 

Therefore, Kayak Marketing Team would like to create an application that will recommend where people should plan their next holidays. The application should be based on real data about:

* Weather 
* Hotels in the area 

The application should then be able to recommend the best destinations and hotels based on the above variables at any given time.

## Goals 🎯

As the project has just started, your team doesn't have any data that can be used to create this application. Therefore, your job will be to: 

* Scrape data from destinations 
* Get weather data from each destination 
* Get hotels' info about each destination
* Store all the information above in a data lake
* Extract, transform and load cleaned data from your datalake to a data warehouse

## Scope of this project 🖼️

Marketing team wants to focus first on the best cities to travel to in France. According <a href="https://one-week-in.com/35-cities-to-visit-in-france/" target="_blank">One Week In.com</a> here are the top-35 cities to visit in France: 

```python 
["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]
```

Your team should focus **only on the above cities for your project**.

## Helpers 🦮

To help you achieve this project, here are a few tips that should help you

### Get weather data with an API 

*   Use https://nominatim.org/ to get the gps coordinates of all the cities (no subscription required) Documentation : https://nominatim.org/release-docs/develop/api/Search/

*   Use https://openweathermap.org/appid (you have to subscribe to get a free apikey) and https://openweathermap.org/api/one-call-api to get some information about the weather for the 35 cities and put it in a DataFrame

*   Determine the list of cities where the weather will be the nicest within the next 7 days For example, you can use the values of daily.pop and daily.rain to compute the expected volume of rain within the next 7 days... But it's only an example, actually you can have different opinions on a what a nice weather would be like 😎 Maybe the most important criterion for you is the temperature or humidity, so feel free to change the rules !

*   Save all the results in a `.csv` file, you will use it later 😉 You can save all the informations that seem important to you ! Don't forget to save the name of the cities, and also to create a column containing a unique identifier (id) of each city (this is important for what's next in the project)

*   Use plotly to display the best destinations on a map

### Scrape Booking.com 

Since BookingHoldings doesn't have aggregated databases, it will be much faster to scrape data directly from booking.com 

You can scrap as many information asyou want, but we suggest that you get at least:

*   hotel name,
*   Url to its booking.com page,
*   Its coordinates: latitude and longitude
*   Score given by the website users
*   Text description of the hotel


### Create your data lake using S3 

Once you managed to build your dataset, you should store into S3 as a csv file. 

### ETL 

Once you uploaded your data onto S3, it will be better for the next data analysis team to extract clean data directly from a Data Warehouse. Therefore, create a SQL Database using AWS RDS, extract your data from S3 and store it in your newly created DB.

## Deliverable 📬

To complete this project, your team should deliver:

* A `.csv` file in an S3 bucket containing enriched information about weather and hotels for each french city

* A SQL Database where we should be able to get the same cleaned data from S3 

* Two maps where you should have a Top-5 destinations and a Top-20 hotels in the area. You can use plotly or any other library to do so. It should look something like this: 

![Map](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/Kayak_best_destination_project.png)

API : Application Programming Interface

## 🔹 1.Data Collection

In [1]:
# 📦 Data handling
import pandas as pd          
import numpy as np        

# 🌐 API & web scraping
import requests              # To call APIs (e.g., OpenWeatherMap)
from bs4 import BeautifulSoup  # To extract data from HTML (for scraping hotels)
import json                  # To handle JSON data from APIs
import re                    # To clean/extract text patterns (like prices)

# 📊 Visualization
import plotly.express as px  
import plotly.io as pio     
pio.renderers.default = "png"  # Make charts static PNGs (better for Jupyter)

# 🛢️ SQL database
from sqlalchemy import create_engine, text  # Connect and query SQL
from sqlalchemy.orm import sessionmaker     # Manage SQL sessions

# ⚙️ Utility
import os                    # Work with files/folders
import time                  # Add pauses (e.g., in scraping loops)
import logging               # Hide unwanted debug messages

## 1.1 📍 Destinations

In [2]:
cities_list = [
    "Mont Saint Michel",
    "St Malo",
    "Bayeux",
    "Le Havre",
    "Rouen",
    "Paris",
    "Amiens",
    "Lille",
    "Strasbourg",
    "Chateau du Haut Koenigsbourg",
    "Colmar",
    "Eguisheim",
    "Besancon",
    "Dijon",
    "Annecy",
    "Grenoble",
    "Lyon",
    "Gorges du Verdon",
    "Bormes les Mimosas",
    "Cassis",
    "Marseille",
    "Aix en Provence",
    "Avignon",
    "Uzes",
    "Nimes",
    "Aigues Mortes",
    "Saintes Maries de la mer",
    "Collioure",
    "Carcassonne",
    "Ariege",
    "Toulouse",
    "Montauban",
    "Biarritz",
    "Bayonne",
    "La Rochelle"
]

In [3]:
## Transform cities_list into a DataFrame
df_cities = pd.DataFrame(cities_list)
df_cities = df_cities.rename(columns={0: "cities"})

In [4]:
from urllib.parse import quote
import requests, time
import pandas as pd

url = 'https://nominatim.openstreetmap.org/search?q={}&format=jsonv2'
headers = {"User-Agent": "Mozilla/5.0"}

lat, lon = [], []

for city in cities_list:
    response = requests.get(url.format(quote(city)), headers=headers)
    if response.status_code == 200:
        data = response.json()
        lat.append(data[0]['lat'] if data else None)
        lon.append(data[0]['lon'] if data else None)
    else:
        print(f"❌ Failed for {city} | Status: {response.status_code}")
        lat.append(None)
        lon.append(None)
    time.sleep(1)  

df_cities['latitude'] = lat
df_cities['longitude'] = lon

In [5]:
df_cities[['cities', 'latitude', 'longitude']].head(10)
df_cities.to_csv("cities_with_coordinates.csv", index=False)

In [6]:
df_cities.head(10)

                         cities    latitude    longitude
0             Mont Saint Michel  48.6359541   -1.5114600
1                       St Malo  49.3146950  -96.9538228
2                        Bayeux  49.2764624   -0.7024738
3                      Le Havre  49.4938975    0.1079732
4                         Rouen  49.4404591    1.0939658
5                         Paris  48.8588897    2.3200410
6                        Amiens  49.8941708    2.2956951
7                         Lille  50.6365654    3.0635282
8                    Strasbourg  48.5846140    7.7507127
9  Chateau du Haut Koenigsbourg  48.2494107    7.3443202

In [7]:
# generate a CSV file 

!open cities_with_coordinates.csv

## 1.2 🌦️ Weather Data

In [8]:

# Your API key
API_KEY = "b2409e3601ddea21c6a341a830d24bfc"

# Empty list to store weather info
weather_data = []

# Loop through each row in your cities DataFrame
for i, row in df_cities.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    city = row['cities']

    # Build API request URL
    url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&units=metric&appid={API_KEY}"
    
    # Make API request
    response = requests.get(url)
    data = response.json()

    # If request is OK, extract weather info
    if response.status_code == 200 and "main" in data:
        weather_data.append({
            "cities": city,
            "temp": data['main']['temp'],
            "temp_min": data['main']['temp_min'],
            "temp_max": data['main']['temp_max'],
            "feels_like": data['main']['feels_like'],
            "humidity": data['main']['humidity'],
            "wind_speed": data['wind']['speed'],
            "weather_main": data['weather'][0]['main'],
            "weather_desc": data['weather'][0]['description']
        })
    else:
        print(f"No data for {city} → {data}")

    time.sleep(1)  # To avoid hitting the API limit

# Convert list to DataFrame
df_weather = pd.DataFrame(weather_data)
df_weather.head()

,cities,temp,temp_min,temp_max,feels_like,humidity,wind_speed,weather_main,weather_desc
0,Mont Saint Michel,27.06,27.06,27.06,26.96,41,3.75,Clear,clear sky
1,St Malo,12.69,12.69,12.69,12.44,93,4.72,Clouds,broken clouds
2,Bayeux,27.14,27.14,27.14,27.42,48,5.89,Clear,clear sky
3,Le Havre,22.51,22.51,24.86,22.85,78,6.17,Clear,clear sky
4,Rouen,28.80,28.80,28.80,29.52,51,4.63,Clear,clear sky

In [9]:
# ✅ Merge weather with cities (for lat/lon info too)
df_final = pd.merge(df_cities, df_weather, on="cities")

# 💾 Save to CSV
df_final.to_csv("cities_weather_full.csv", index=False)

# Preview result
df_final.head()

,cities,latitude,longitude,temp,temp_min,temp_max,feels_like,humidity,wind_speed,weather_main,weather_desc
0,Mont Saint Michel,48.6359541,-1.5114600,27.06,27.06,27.06,26.96,41,3.75,Clear,clear sky
1,St Malo,49.3146950,-96.9538228,12.69,12.69,12.69,12.44,93,4.72,Clouds,broken clouds
2,Bayeux,49.2764624,-0.7024738,27.14,27.14,27.14,27.42,48,5.89,Clear,clear sky
3,Le Havre,49.4938975,0.1079732,22.51,22.51,24.86,22.85,78,6.17,Clear,clear sky
4,Rouen,49.4404591,1.0939658,28.80,28.80,28.80,29.52,51,4.63,Clear,clear sky

In [10]:
# Studying only current weather is too limited.  
# We use Open-Meteo to get free 7-day forecasts (temp, rain, clouds, etc.)  
# Unlike OpenWeather, Open-Meteo needs no API key and no paid plan.

In [11]:
!pip install openmeteo-requests

Requirement already satisfied: openmeteo-requests in /opt/anaconda3/lib/python3.12/site-packages (1.6.0)
Requirement already satisfied: niquests>=3.14.1 in /opt/anaconda3/lib/python3.12/site-packages (from openmeteo-requests) (3.14.1)
Requirement already satisfied: openmeteo-sdk>=1.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from openmeteo-requests) (1.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from niquests>=3.14.1->openmeteo-requests) (3.3.2)
Requirement already satisfied: urllib3-future<3,>=2.12.900 in /opt/anaconda3/lib/python3.12/site-packages (from niquests>=3.14.1->openmeteo-requests) (2.13.901)
Requirement already satisfied: wassima<2,>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from niquests>=3.14.1->openmeteo-requests) (1.2.2)
Requirement already satisfied: flatbuffers==25.2.10 in /opt/anaconda3/lib/python3.12/site-packages (from openmeteo-sdk>=1.20.1->openmeteo-requests) (25.2.10)
Requirement already satisfied: h11<1.0.0,>=0.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from urllib3-future<3,>=2.12.900->niquests>=3.14.1->openmeteo-requests) (0.14.0)
Requirement already satisfied: jh2<6.0.0,>=5.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from urllib3-future<3,>=2.12.900->niquests>=3.14.1->openmeteo-requests) (5.0.9)
Requirement already satisfied: qh3<2.0.0,>=1.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from urllib3-future<3,>=2.12.900->niquests>=3.14.1->openmeteo-requests) (1.5.3)

In [12]:
!pip install requests-cache retry-requests

Requirement already satisfied: requests-cache in /opt/anaconda3/lib/python3.12/site-packages (1.1.1)
Requirement already satisfied: retry-requests in /opt/anaconda3/lib/python3.12/site-packages (2.0.0)
Requirement already satisfied: attrs>=21.2 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache) (23.1.0)
Requirement already satisfied: cattrs>=22.2 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache) (24.1.3)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache) (3.10.0)
Requirement already satisfied: requests>=2.22 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache) (2.32.3)
Requirement already satisfied: url-normalize>=1.4 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache) (2.2.1)
Requirement already satisfied: urllib3>=1.25.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache) (2.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.22->requests-cache) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.22->requests-cache) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.22->requests-cache) (2025.8.3)

In [13]:
! pip install --upgrade attrs

Requirement already satisfied: attrs in /opt/anaconda3/lib/python3.12/site-packages (23.1.0)
Collecting attrs
  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Using cached attrs-25.3.0-py3-none-any.whl (63 kB)
Installing collected packages: attrs
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.12.3 requires botocore<1.34.70,>=1.34.41, but you have botocore 1.40.7 which is incompatible.
Successfully installed attrs-25.3.0

In [14]:
! pip uninstall attrs requests-cache -y

Found existing installation: attrs 25.3.0
Uninstalling attrs-25.3.0:
  Successfully uninstalled attrs-25.3.0
Found existing installation: requests-cache 1.1.1
Uninstalling requests-cache-1.1.1:
  Successfully uninstalled requests-cache-1.1.1

In [15]:
! pip install attrs==23.1.0 requests-cache==1.1.1

Collecting attrs==23.1.0
  Using cached attrs-23.1.0-py3-none-any.whl.metadata (11 kB)
Collecting requests-cache==1.1.1
  Using cached requests_cache-1.1.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: cattrs>=22.2 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache==1.1.1) (24.1.3)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache==1.1.1) (3.10.0)
Requirement already satisfied: requests>=2.22 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache==1.1.1) (2.32.3)
Requirement already satisfied: url-normalize>=1.4 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache==1.1.1) (2.2.1)
Requirement already satisfied: urllib3>=1.25.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache==1.1.1) (2.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.22->requests-cache==1.1.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.22->requests-cache==1.1.1) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.22->requests-cache==1.1.1) (2025.8.3)
Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Using cached requests_cache-1.1.1-py3-none-any.whl (60 kB)
Installing collected packages: attrs, requests-cache
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
trio 0.30.0 requires attrs>=23.2.0, but you have attrs 23.1.0 which is incompatible.
aiobotocore 2.12.3 requires botocore<1.34.70,>=1.34.41, but you have botocore 1.40.7 which is incompatible.
Successfully installed attrs-23.1.0 requests-cache-1.1.1

In [16]:
# Forecast for 7 days 

DAILY = "temperature_2m_min,temperature_2m_max,precipitation_sum,cloudcover_mean,windspeed_10m_max"

def get_city_forecast(row):
    url = (
        "https://api.open-meteo.com/v1/forecast"
        f"?latitude={row.latitude}&longitude={row.longitude}"
        f"&daily={DAILY}&forecast_days=7&timezone=auto"
    )
    resp = requests.get(url).json()

    # Debug: skip cities with no daily forecast
    if "daily" not in resp:
        print(f"⚠️ No daily data for {row.cities}. Response:", resp)
        return pd.DataFrame()

    d = resp["daily"]

    return pd.DataFrame({
        "city": row.cities,
        "latitude": row.latitude,
        "longitude": row.longitude,
        "date": pd.to_datetime(d["time"]),
        "temp_min": d["temperature_2m_min"],
        "temp_max": d["temperature_2m_max"],
        "precipitation": d["precipitation_sum"],
        "cloudcover": d["cloudcover_mean"],
        "wind_speed": d["windspeed_10m_max"]
    })

# Run for all cities, skipping empty ones
df_forecast = pd.concat(
    [get_city_forecast(r) for _, r in df_cities.iterrows() if not get_city_forecast(r).empty],
    ignore_index=True
)

# Save CSV
df_forecast.to_csv("7_day_weather_forecast.csv", index=False)
print("✅ Forecast saved for all cities")
df_forecast.head()

✅ Forecast saved for all cities

,city,latitude,longitude,date,temp_min,temp_max,precipitation,cloudcover,wind_speed
0,Mont Saint Michel,48.6359541,-1.5114600,2025-08-12,17.8,29.8,0.0,11,18.9
1,Mont Saint Michel,48.6359541,-1.5114600,2025-08-13,17.0,25.2,0.0,87,12.7
2,Mont Saint Michel,48.6359541,-1.5114600,2025-08-14,17.0,22.8,0.0,64,20.6
3,Mont Saint Michel,48.6359541,-1.5114600,2025-08-15,16.7,32.1,0.0,11,21.4
4,Mont Saint Michel,48.6359541,-1.5114600,2025-08-16,20.0,31.7,0.0,19,22.1

In [17]:
# 📊 Monthly Historical Weather for 2024 for All Cities
# Using Open-Meteo Historical API (free, no key required)


# Variables to retrieve
DAILY = "temperature_2m_max,temperature_2m_min,precipitation_sum"

def get_monthly_2024(row):
    url = (
        "https://archive-api.open-meteo.com/v1/archive"
        f"?latitude={row.latitude}&longitude={row.longitude}"
        f"&daily={DAILY}&start_date=2024-01-01&end_date=2024-12-31"
        "&timezone=auto"
    )
    resp = requests.get(url).json()
    
    if "daily" not in resp:
        print(f"⚠️ No data for {row.cities}")
        return pd.DataFrame()

    d = resp["daily"]
    df = pd.DataFrame({
        "date": pd.to_datetime(d["time"]),
        "temp_min": d["temperature_2m_min"],
        "temp_max": d["temperature_2m_max"],
        "precipitation": d["precipitation_sum"]
    })

    # Add city name & month
    df["city"] = row.cities
    df["month"] = df["date"].dt.to_period("M")
    
    # Aggregate monthly means
    return df.groupby(["city", "month"], as_index=False).mean()

# Loop through all cities
df_weather_2024 = pd.concat(
    [get_monthly_2024(r) for _, r in df_cities.iterrows()],
    ignore_index=True
)

# Save to CSV
df_weather_2024.to_csv("monthly_weather_2024.csv", index=False)
print("✅ 2024 monthly weather saved to 'monthly_weather_2024.csv'")
df_weather_2024.head()

✅ 2024 monthly weather saved to 'monthly_weather_2024.csv'

,city,month,date,temp_min,temp_max,precipitation
0,Mont Saint Michel,2024-01,2024-01-16 00:00:00,2.235484,8.396774,2.800000
1,Mont Saint Michel,2024-02,2024-02-15 00:00:00,7.144828,11.924138,3.813793
2,Mont Saint Michel,2024-03,2024-03-16 00:00:00,5.445161,12.738710,2.509677
3,Mont Saint Michel,2024-04,2024-04-15 12:00:00,7.180000,14.500000,2.300000
4,Mont Saint Michel,2024-05,2024-05-16 00:00:00,10.135484,17.345161,3.645161

## 1.3 🏨 Hotel Data

In [18]:
# Scraping Booking.com for hotel data in one city

# 2. Define the city search URL
# This is the Booking.com search page for Paris (in French)
city_url = "https://www.booking.com/searchresults.fr.html?ss=Paris&lang=fr&dest_type=city&nflt="

# 3. Set up headers to pretend we are a browser
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/114.0.0.0 Safari/537.36"
}

# 4. Send request and parse HTML with BeautifulSoup

response = requests.get(city_url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

# 5. Create a list to store hotel data

hotels = []
# 6. Loop through each hotel block on the page

for hotel_block in soup.select("div[data-testid='property-card']"):

    # ----- 6.1 Extract hotel name -----
    name_tag = hotel_block.select_one("div[data-testid='title']")
    name = name_tag.get_text(strip=True) if name_tag else None

    # ----- 6.2 Extract hotel link -----
    link_tag = hotel_block.select_one("a[data-testid='title-link']")
    link = "https://www.booking.com" + link_tag["href"].split("?")[0] if link_tag else None

    # ----- 6.3 Extract hotel rating -----
    rating_tag = hotel_block.select_one("div[data-testid='review-score'] div")
    rating = rating_tag.get_text(strip=True) if rating_tag else None

    # Add hotel info to list
    hotels.append({
        "Name": name,
        "Link": link,
        "Rating": rating
    })

# 7. Convert list to DataFrame and save as CSV

df = pd.DataFrame(hotels)
df.to_csv("paris_hotels.csv", index=False)

# 8. Show results
print(df.head())  # Display first rows in terminal
print("✅ Data saved to paris_hotels.csv")

Empty DataFrame
Columns: []
Index: []
✅ Data saved to paris_hotels.csv

In [19]:
# Scraping Booking.com for hotels in cities from df_cities

all_hotels = []

for _, row in df_cities.iterrows():
    city_name = row["cities"]      # City name  DataFrame
    lat = row["latitude"]          # Latitude (not used in URL, but we keep it)
    lon = row["longitude"]         # Longitude (not used in URL, but we keep it)

    print(f"Scraping hotels in {city_name}...")

    # Booking.com search URL for this city (in French)
    city_url = f"https://www.booking.com/searchresults.fr.html?ss={city_name}&lang=fr&dest_type=city&nflt="

    # Headers to pretend to be a browser
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/114.0.0.0 Safari/537.36"
    }

    # Request the page and parse it
    response = requests.get(city_url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    # Extract hotels on the page
    for hotel_block in soup.select("div[data-testid='property-card']"):
        name_tag = hotel_block.select_one("div[data-testid='title']")
        name = name_tag.get_text(strip=True) if name_tag else None

        link_tag = hotel_block.select_one("a[data-testid='title-link']")
        link = "https://www.booking.com" + link_tag["href"].split("?")[0] if link_tag else None

        rating_tag = hotel_block.select_one("div[data-testid='review-score'] div")
        rating = rating_tag.get_text(strip=True) if rating_tag else None

        all_hotels.append({
            "City": city_name,
            "Latitude": lat,
            "Longitude": lon,
            "Name": name,
            "Link": link,
            "Rating": rating
        })

# Convert all results to DataFrame and save
df_hotels = pd.DataFrame(all_hotels)
df_hotels.to_csv("all_cities_hotels.csv", index=False)
print(df_hotels.head())
print("✅ Data saved to all_cities_hotels.csv")

Scraping hotels in Mont Saint Michel...
Scraping hotels in St Malo...
Scraping hotels in Bayeux...
Scraping hotels in Le Havre...
Scraping hotels in Rouen...
Scraping hotels in Paris...
Scraping hotels in Amiens...
Scraping hotels in Lille...
Scraping hotels in Strasbourg...
Scraping hotels in Chateau du Haut Koenigsbourg...
Scraping hotels in Colmar...
Scraping hotels in Eguisheim...
Scraping hotels in Besancon...
Scraping hotels in Dijon...
Scraping hotels in Annecy...
Scraping hotels in Grenoble...
Scraping hotels in Lyon...
Scraping hotels in Gorges du Verdon...
Scraping hotels in Bormes les Mimosas...
Scraping hotels in Cassis...
Scraping hotels in Marseille...
Scraping hotels in Aix en Provence...
Scraping hotels in Avignon...
Scraping hotels in Uzes...
Scraping hotels in Nimes...
Scraping hotels in Aigues Mortes...
Scraping hotels in Saintes Maries de la mer...
Scraping hotels in Collioure...
Scraping hotels in Carcassonne...
Scraping hotels in Ariege...
Scraping hotels in Toulouse...
Scraping hotels in Montauban...
Scraping hotels in Biarritz...
Scraping hotels in Bayonne...
Scraping hotels in La Rochelle...
      City    Latitude    Longitude                                     Name  \
0  St Malo  49.3146950  -96.9538228           HÃ´tel France et Chateaubriand
1  St Malo  49.3146950  -96.9538228                  HÃ´tel Anne de Bretagne
2  St Malo  49.3146950  -96.9538228  Golden Tulip Saint Maloâ Le Grand BÃ©
3  St Malo  49.3146950  -96.9538228                       Oceania Saint Malo
4  St Malo  49.3146950  -96.9538228               Kyriad Prestige Saint-Malo

                                                Link                Rating
0  https://www.booking.comhttps://www.booking.com...  Avec une note de 7,9
1  https://www.booking.comhttps://www.booking.com...  Avec une note de 8,8
2  https://www.booking.comhttps://www.booking.com...  Avec une note de 8,6
3  https://www.booking.comhttps://www.booking.com...  Avec une note de 8,8
4  https://www.booking.comhttps://www.booking.com...  Avec une note de 8,8
✅ Data saved to all_cities_hotels.csv

## 1.4 🗃️ Organize my Data

In [20]:
#Store all the information above in a data lake

! pip install --upgrade "boto3>=1.34" "botocore>=1.34" "s3transfer>=0.10"
# if it still complains, force a clean reinstall:
# pip uninstall -y boto3 botocore s3transfer
# pip install boto3

Requirement already satisfied: boto3>=1.34 in /opt/anaconda3/lib/python3.12/site-packages (1.40.7)
Requirement already satisfied: botocore>=1.34 in /opt/anaconda3/lib/python3.12/site-packages (1.40.7)
Requirement already satisfied: s3transfer>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (0.13.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from boto3>=1.34) (1.0.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/anaconda3/lib/python3.12/site-packages (from botocore>=1.34) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/anaconda3/lib/python3.12/site-packages (from botocore>=1.34) (2.5.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.34) (1.16.0)

In [21]:
! conda remove -y boto3 botocore s3transfer
! conda install -y -c conda-forge boto3 botocore s3transfer

PackagesNotFoundError: The following packages are missing from the target environment:
  - s3transfer
  - boto3


Channels:
 - conda-forge
 - defaults
 - plotly
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - boto3
    - botocore
    - s3transfer


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiobotocore-2.24.0         |     pyhe01879c_0          78 KB  conda-forge
    boto3-1.39.11              |     pyhd8ed1ab_0          82 KB  conda-forge
    botocore-1.39.11           |pyge310_1234567_0         7.6 MB  conda-forge
    ca-certificates-2025.8.3   |       hbd8a1cb_0         151 KB  conda-forge
    certifi-2025.8.3           |     pyhd8ed1ab_0         155 KB  conda-forge
    openssl-3.5.2              |       he92f556_0         2.9 MB  conda-forge
    s3transfer-0.13.1          |     pyhd8ed1ab_0          64 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        11.0 MB

The following NEW packages will be INSTALLED:

  boto3              conda-forge/noarch::boto3-1.39.11-pyhd8ed1ab_0
  s3transfer         conda-forge/noarch::s3transfer-0.13.1-pyhd8ed1ab_0

The following packages will be UPDATED:

  aiobotocore        pkgs/main/osx-arm64::aiobotocore-2.12~ --> conda-forge/noarch::aiobotocore-2.24.0-pyhe01879c_0
  botocore           pkgs/main/osx-arm64::botocore-1.34.69~ --> conda-forge/noarch::botocore-1.39.11-pyge310_1234567_0
  ca-certificates    pkgs/main/osx-arm64::ca-certificates-~ --> conda-forge/noarch::ca-certificates-2025.8.3-hbd8a1cb_0
  certifi            pkgs/main/osx-arm64::certifi-2024.12.~ --> conda-forge/noarch::certifi-2025.8.3-pyhd8ed1ab_0
  openssl                                  3.4.0-h81ee809_1 --> 3.5.2-he92f556_0



Downloading and Extracting Packages:
botocore-1.39.11     | 7.6 MB    |                                       |   0%
openssl-3.5.2        | 2.9 MB    |                                       |   0%

certifi-2025.8.3     | 155 KB    |                                       |   0%


ca-certificates-2025 | 151 KB    |                                       |   0%



boto3-1.39.11        | 82 KB     |                                       |   0%




aiobotocore-2.24.0   | 78 KB     |                                       |   0%





botocore-1.39.11     | 7.6 MB    |                                       |   0%


botocore-1.39.11     | 7.6 MB    | 4                                     |   1%


ca-certificates-2025 | 151 KB    | #######################5              |  64%


ca-certificates-2025 | 151 KB    | ##################################### | 100%
openssl-3.5.2        | 2.9 MB    | 1                                     |   1%

certifi-2025.8.3     | 155 KB    | ###8                                  |  10%



boto3-1.39.11        | 82 KB     | #######2                              |  20%



boto3-1.39.11        | 82 KB     | ##################################### | 100%


ca-certificates-2025 | 151 KB    | ##################################### | 100%



botocore-1.39.11     | 7.6 MB    | #                                     |   3%
openssl-3.5.2        | 2.9 MB    | #1                                    |   3%

certifi-2025.8.3     | 155 KB    | ######################9               |  62%

certifi-2025.8.3     | 155 KB    | ##################################### | 100%




aiobotocore-2.24.0   | 78 KB     | #######6                              |  21%





s3transfer-0.13.1    | 64 KB     | #########2                            |  25%




aiobotocore-2.24.0   | 78 KB     | ##################################### | 100%





s3transfer-0.13.1    | 64 KB     | ##################################### | 100%

certifi-2025.8.3     | 155 KB    | ##################################### | 100%





s3transfer-0.13.1    | 64 KB     | ##################################### | 100%




botocore-1.39.11     | 7.6 MB    | ##4                                   |   7%
botocore-1.39.11     | 7.6 MB    | ####6                                 |  13%
openssl-3.5.2        | 2.9 MB    | ####3                                 |  12%
openssl-3.5.2        | 2.9 MB    | #######2                              |  20%
openssl-3.5.2        | 2.9 MB    | ##########6                           |  29%
botocore-1.39.11     | 7.6 MB    | ########                              |  22%
botocore-1.39.11     | 7.6 MB    | ########8                             |  24%
openssl-3.5.2        | 2.9 MB    | ##########################6           |  72%
openssl-3.5.2        | 2.9 MB    | ##################################### | 100%






















Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [22]:
import boto3, botocore, s3transfer
print("boto3:", boto3.__version__)
print("botocore:", botocore.__version__)
print("s3transfer:", s3transfer.__version__)

boto3: 1.39.11
botocore: 1.39.11
s3transfer: 0.13.1

In [24]:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ListBucket",
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": "arn:aws:s3:::kayakdatalake"
    },
    {
      "Sid": "RWObjects",
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:PutObjectTagging"
      ],
      "Resource": "arn:aws:s3:::kayakdatalake/*"
    }
  ]
}

{'Version': '2012-10-17',
 'Statement': [{'Sid': 'ListBucket',
   'Effect': 'Allow',
   'Action': ['s3:ListBucket'],
   'Resource': 'arn:aws:s3:::kayakdatalake'},
  {'Sid': 'RWObjects',
   'Effect': 'Allow',
   'Action': ['s3:GetObject',
    's3:PutObject',
    's3:DeleteObject',
    's3:PutObjectTagging'],
   'Resource': 'arn:aws:s3:::kayakdatalake/*'}]}

In [29]:
import boto3, os

session = boto3.Session(region_name="eu-west-3")
s3 = session.client("s3")

bucket_name = "kayakdatalake"
files = [
    "7_day_weather_forecast.csv",
    "all_cities_hotels.csv",
    "cities_weather_full.csv",
    "monthly_weather_2024.csv"
]

for f in files:
    key = f"raw/{os.path.basename(f)}"
    s3.upload_file(f, bucket_name, key)
    print(f"✔ Uploaded s3://{bucket_name}/{key}")

✔ Uploaded s3://kayakdatalake/raw/7_day_weather_forecast.csv
✔ Uploaded s3://kayakdatalake/raw/all_cities_hotels.csv
✔ Uploaded s3://kayakdatalake/raw/cities_weather_full.csv
✔ Uploaded s3://kayakdatalake/raw/monthly_weather_2024.csv

## 🔹 2. Data Cleaning & Transformation (ETL)

In [30]:
! pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.12/site-packages (2.0.0)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.12/site-packages (2.9.10)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy) (4.14.1)

In [ ]:
! pip install python-dotenv

Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.12/site-packages (0.21.0)

In [8]:
%pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp312-cp312-macosx_14_0_arm64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.10-cp312-cp312-macosx_14_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 9.3 MB/s eta 0:00:00a 0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [13]:
from dotenv import load_dotenv
import os

load_dotenv(dotenv_path=".env", override=True)  # <-- force refresh

for k in ["PGHOST","PGPORT","PGDB","PGUSER"]:
    print(k, "=>", repr(os.getenv(k)))

PGHOST => 'kayak-db.cnsg2s0ag476.eu-west-3.rds.amazonaws.com'
PGPORT => '5432'
PGDB => 'postgres'
PGUSER => 'postgres'

In [18]:
from sqlalchemy import create_engine # bridge between  Python code and my PostgreSQL database.

host = os.getenv("PGHOST").strip()
port = os.getenv("PGPORT").strip()
user = os.getenv("PGUSER").strip()
pwd  = os.getenv("PGPASSWORD").strip()

db   = os.getenv("PGDB").strip()  # should be 'postgres'

url = f"postgresql+psycopg://{user}:{pwd}@{host}:{port}/{db}?sslmode=require"
print("Connecting to:", url.replace(pwd, "*****"))  # sanity-check (password masked)

engine = create_engine(url, pool_pre_ping=True)

with engine.begin() as conn:
    print(conn.exec_driver_sql("select current_database(), version()").fetchone())

Connecting to: postgresql+psycopg://postgres:*****@kayak-db.cnsg2s0ag476.eu-west-3.rds.amazonaws.com:5432/postgres?sslmode=require
('postgres', 'PostgreSQL 17.4 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 12.4.0, 64-bit')

In [19]:
# Create a schema in PostgreSQL for the project

from sqlalchemy import text

with engine.begin() as con:
    con.execute(text("CREATE SCHEMA IF NOT EXISTS kayak;"))

In [20]:
# Upload all CSVs from S3 to PostgreSQL

%pip install -q boto3  # install AWS SDK if not already installed

import boto3, pandas as pd
from io import StringIO

# S3 bucket name
bucket = "kayakdatalake"

# Mapping of S3 file paths to PostgreSQL table names
files = {
    "raw/cities_weather_full.csv":   "cities_weather_full",
    "raw/all_cities_hotels.csv":     "all_cities_hotels",
    "raw/7_day_weather_forecast.csv":"weather_7day",
    "raw/monthly_weather_2024.csv":  "weather_monthly",
}

# Create S3 client
s3 = boto3.client("s3")

# Loop through all files and load into PostgreSQL
for key, table in files.items():
    obj = s3.get_object(Bucket=bucket, Key=key)
    df = pd.read_csv(StringIO(obj["Body"].read().decode("utf-8")))
    df.to_sql(table, engine, schema="kayak", if_exists="replace", index=False)
    print(f"Loaded {key} → kayak.{table} ({len(df)} rows)")

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.24.0 requires botocore<1.39.12,>=1.39.9, but you have botocore 1.40.8 which is incompatible.
Note: you may need to restart the kernel to use updated packages.
Loaded raw/cities_weather_full.csv → kayak.cities_weather_full (35 rows)
Loaded raw/all_cities_hotels.csv → kayak.all_cities_hotels (625 rows)
Loaded raw/7_day_weather_forecast.csv → kayak.weather_7day (245 rows)
Loaded raw/monthly_weather_2024.csv → kayak.weather_monthly (420 rows)

## 🔹 3. Final part : Plotting

In [103]:
import pandas as pd, plotly.express as px

# Load once, compute daily avg, then city-level avg
df = pd.read_sql(
    "SELECT city, latitude, longitude, temp_min, temp_max FROM kayak.weather_7day",
    engine
)
df["avg_temp"] = (pd.to_numeric(df["temp_min"]) + pd.to_numeric(df["temp_max"])) / 2

# Average per city (keeps one row per city with its coords)
plot_df = (df.groupby(["city","latitude","longitude"], as_index=False)["avg_temp"]
             .mean()
             .dropna(subset=["avg_temp"]))

# Plot
fig = px.scatter_mapbox(
    plot_df, lat="latitude", lon="longitude",
    color="avg_temp", hover_name="city",
    size=[10]*len(plot_df), color_continuous_scale="Turbo",
    zoom=5, height=520
)
fig.update_layout(mapbox_style="open-street-map", margin=dict(l=0,r=0,t=0,b=0))
fig.show()

In [97]:
## Top-5 warmest cities under 30°C

# Load 7-day data
df = pd.read_sql("SELECT city, latitude, longitude, temp_min, temp_max FROM kayak.weather_7day", engine)

# Average temp per city (France only)
df["avg"] = (pd.to_numeric(df.temp_min) + pd.to_numeric(df.temp_max)) / 2
city_avg = (df.query("41 <= latitude <= 51.5 and -5 <= longitude <= 9.5")
              .groupby(["city","latitude","longitude"], as_index=False)["avg"].mean())

# Top-5 warmest cities under 30°C
top5 = city_avg.query("avg < 30").nlargest(5, "avg")

# Map
px.scatter_mapbox(top5, lat="latitude", lon="longitude", hover_name="city",
                  color="avg", color_continuous_scale="Turbo", size=[12]*len(top5),
                  zoom=5, height=520).update_layout(mapbox_style="open-street-map").show()

In [ ]:
import plotly.graph_objects as go

fig = go.Figure()

# Top 5 cities (big blue markers with city names)
fig.add_trace(go.Scattermapbox(
    lat=top5["latitude"], lon=top5["longitude"],
    mode="markers+text",
    marker=dict(size=18, color="royalblue"),
    text=top5["city"],
    textposition="top center",
    name="City (Top-5)"
))

# Top 20 hotels (red markers, hover shows only the name)
fig.add_trace(go.Scattermapbox(
    lat=hotels["lat"], lon=hotels["lon"],
    mode="markers",
    marker=dict(size=7, color="crimson", opacity=0.75),
    text=hotels["name"],  
    hoverinfo="text",
    name="Hotel (Top-20/city)"
))

fig.update_layout(
    mapbox_style="open-street-map",
    mapbox=dict(center=dict(lat=46, lon=2), zoom=5.2),
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(x=0.01, y=0.99)
)

fig.show()

## 📌 Limitations & Next Steps

Right now, our analysis only looks at the 7-day weather forecast. That’s helpful if someone is planning a last-minute trip, but it’s not very useful for most travelers.

In reality, many people book their holidays 3 to 6 months ahead, so short-term forecasts don’t give them the information they need to pick the right time to travel.

To make this tool more practical, the next step would be to include monthly averages and long-term climate trends. With that, we could:

Show the best months to visit each destination.

Compare places based on seasonal weather patterns.

Provide a more reliable guide for travelers who plan well in advance.